name: Ubuntu

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get install libglib2.0-dev libgtk-3-dev
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}

      - name: Build Project | All
        run: |
          cargo build --verbose
          cargo build --verbose --release

      - name: Run Tests | All
        run: |
          cargo test --verbose
          cargo test --verbose --release